---

- name: Add official elasticsearch apt key
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add official elasticsearch apt repo
  # when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_version }}/debian stable main"
    state: present

- name: Install latest elasticsearch server
  # when: ansible_os_family == "Debian"
  apt: 
    pkg:
      - elasticsearch
      - openjdk-7-jre-headless
    state: latest
    update_cache: yes
    cache_valid_time: 180

- name: Check elasticsearch config file
  template:
    src: elasticsearch.yml.j2
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: root
    backup: yes
    mode: 0644
  notify: Restart Elasticsearch

- name: Install elasticsearch plugins
  command: "/usr/share/elasticsearch/bin/plugin -i {{ item.name }}"
  when: elasticsearch_plugins is defined
  register: plugin_installed
  failed_when:
    - plugin_installed.rc != 74
    - plugin_installed.rc != 0
  changed_when:
    - '"already exists" not in plugin_installed.stdout'
    - plugin_installed.rc != 74
  with_items: elasticsearch_plugins

- name: Check what elasticsearch is working and enabled
  service:
    name: elasticsearch
    state: started
    enabled: yes
